services:
  redis-stack-server:
    image: redis/redis-stack-server:latest #由于本地我安装了redis inst，所以只装服务端
    ports:
      - "10001:6379" #本地装了个redis，防止端口冲突，故修改为 10001
    volumes:
      - redis-stack-data:/data
      - redis-stack-config:/redis-stack.cof
    networks:
      redis-stack-net
  neo4j:
    image: neo4j:latest
    ports:
      - "7473:7473"
      - "7474:7474"
      - "7687:7687"
    volumes:
      - neo4j-data:/data
      - neo4j-plugins:/plugins
    networks:
      neo4j-net

  mysql:
    image: mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: mysql-root #指定mysql环境变量，root用户的密码为123456. 方便以后忘了密码 去容器里echo打印环境变量出来
    volumes:
    # (this is just an example, not intended to be a production configuration)
      - mysql-log: /var/log/mysql #映射日志目录，宿主机:容器
      - mysql-data: /var/lib/mysql #映射数据目录，宿主机:容器
      - mysql-conf: /etc/mysql #映射配置目录，宿主机:容器
      - /etc/localtime: /etc/localtime:ro #让容器的时钟与宿主机时钟同步，避免时区的问题，ro是read only的意思，就是只读。

  volumes:
    redis-stack-config
    neo4j-net
    mysql-log
    mysql-data
    mysql-conf
    /etc/localtime

  networks:
    redis-stack-net:
      driver: bridge