# ******各AI厂商配置（含开源）等配置 *******

## MySQL 数据源配置
spring:
  ai:
    # openai 需要在pom.xml中以来openai starter包
    openai:
      api-key: ${OPENAI_API_KEY:sk-VZk8lv2eLgLpsgO39083D3D620Fe46179d8c6e032d33A699}
      base-url: https://api.xty.app #官方：https://api.openai.com/
      chat:
        options:
          model: gpt-3.5-turbo #gpt-3.5-turbo dall-e-3
          temperature: 0.9
    # 阿里灵积
    dash-scope:
      api-key: ${DASHSCOPE_API_KEY:}
      chat:
        options:
          model: qwen-max
      embedding:
        options:
          model: text-embedding-v2
      image:
        options:
          model: wanx-v1
    vectorstore:
      redis:
        initialize-schema: true